<?php if (!defined('ABSPATH')) exit; get_header(); ?>

<section class="page-hero"><div class="container">
  <div class="crumbs"><a href="/">Home</a> / Photo Credits</div>
  <h1>Photo Credits</h1>
  <p class="lead">New Orleans architectural photography used on this site, courtesy of Wikimedia Commons contributors, with thanks. These images represent New Orleans neighborhoods and will be progressively replaced with our own listing and neighborhood photography.</p>
</div></section>

<section class="section"><div class="container" style="max-width:820px">
  <ul style="list-style:none;padding:0;margin:0">
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Garden District mansion, Coliseum St</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Coliseum_Street%2C_Garden_District%2C_New_Orleans%2C_April_2023_-_Mansion.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Hoffman Mansion, Garden District</strong> &mdash; photo by Infrogmation</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Hoffman_Mansion%2C_Prytania_%26_Harmony%2C_Garden_District_New_Orleans_December_2024_-_05.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Garden District mansion</strong> &mdash; photo by Dan Lang</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/2.0" target="_blank" rel="noopener">CC BY-SA 2.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:New_Orleans_March_2008_-_Garden_District_Mansion.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>French Quarter cast-iron gallery</strong> &mdash; photo by David Ohmer</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener">CC BY 2.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:New_Orleans_-_French_Quarter_%22Cast-Iron_Balcony%22_October_2019.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Creole cottage, Faubourg Marigny</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:New_Marigny_New_Orleans_29th_May_2019_Creole_cottage_at_Marais_%26_Spain_Streets.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Creole cottage, Bywater</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:New_Orleans_in_August_Upper_Bywater_Creole_Cottage.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>St. Charles Ave streetcar, Uptown</strong> &mdash; photo by Infrogmation</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Streetcar_on_Saint_Charles_Avenue%2C_Uptown_New_Orleans%2C_12_March_2024_-_10.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Lakeview home</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Lakeview_New_Orleans_House_Sept_2017_01.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Mid-City home, Orleans Ave</strong> &mdash; photo by Infrogmation</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Orleans_Avenue%2C_Mid-City_New_Orleans_Nov_2024_-_House_with_flag.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Shotgun house, Irish Channel</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by/2.0" target="_blank" rel="noopener">CC BY 2.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File:Shotgun_House%2C_Irish_Channel%2C_New_Orleans_01.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Lanaux Mansion, Esplanade Avenue</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/4.0" target="_blank" rel="noopener">CC BY-SA 4.0</a> &middot; <a href="https://commons.wikimedia.org/wiki/File%3ANew_Orleans_2007_Lanaux_Mansion_2.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
    <li style="display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);flex-wrap:wrap"><span><strong>Italianate mansion, Esplanade Ridge</strong> &mdash; photo by Infrogmation of New Orleans</span><span style="color:var(--muted);font-size:.9rem"><a href="https://creativecommons.org/licenses/by-sa/2.5" target="_blank" rel="noopener">CC BY-SA 2.5</a> &middot; <a href="https://commons.wikimedia.org/wiki/File%3AEsplanade_7Wd_Mansion_Foti.jpg" target="_blank" rel="noopener">Wikimedia Commons</a></span></li>
  </ul>
</div></section>

<?php get_footer(); ?>
